### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by evolgenomology** [GDKO/SCUBAT2#2]
```
/usr/local/lib/python2.7/dist-packages/Bio/SearchIO/__init__.py:211: BiopythonExperimentalWarning: Bio.SearchIO is an experimental submodule which may undergo significant changes prior to its future official release.
  BiopythonExperimentalWarning)
Program started: Wed Oct  5 15:33:18 2016
Processing BLAST xml...100.00%
Calculating stats...100.00%
Creating connections...100.00%
Traceback (most recent call last):
  File "/home/philipp/bioProgs/SCUBAT2/SCUBAT_v2.py", line 582, in <module>
    scaffold_file.write('>Path_' + str(i) +'_' + str(path) + '\n' + string_of_ns.join([getContig(contigs,node) for node in path]) + '\n')
  File "/home/philipp/bioProgs/SCUBAT2/SCUBAT_v2.py", line 272, in getContig
    return str(Seq(ctgs[node[:-2]]).reverse_complement())
KeyError: 'scaffold1838|size12660'
```

**Comment by GDKO** [comment]
What is the command you used?

**Comment by evolgenomology** [comment]
`SCUBAT_v2.py -b XenoAZTrinity.bln.PacBio_l7.run7-j3-i3.scaffolds.5xml -f XenoAZTrinity.bln.PacBio_l7.run7-j3-i3.scaffolds.5xml -max 10000`

I guess the "|" is the problem.

**Comment by GDKO** [comment]
-f is for fasta file not xml

**Comment by evolgenomology** [comment]
Haha, no!!!!!!!

**Comment by evolgenomology** [comment]
You are right. Sorry mate. ;-)

**Comment by GDKO** [comment]
You are better than this :)

**Comment by evolgenomology** [comment]
Not when I am at trying to assemble and in-between have to run to the microscope to find tiny worms in loads of Yorkshire sand...

**Comment by GDKO** [comment]
Sujai thinks it is the London air!

**Comment by evolgenomology** [comment]
![camerazoom-20161005163842249](https://cloud.githubusercontent.com/assets/2168430/19120376/7ded2898-8b1a-11e6-8bf3-4c93f07a76a1.jpg)
Unlikely....

**Comment by evolgenomology** [comment]
See the pic, am equipped.

**Comment by GDKO** [comment]
:)
